lane :test do
  appicon(appicon_image_file: 'spec/fixtures/Themoji.png',
    appicon_devices: [:ipad, :iphone, :'ios-marketing'])
end

lane :android do
  android_appicon(appicon_image_file: 'spec/fixtures/Themoji.png',
    appicon_devices: [:phone, :tablet],
    appicon_path: 'app/res/mipmap')
end
