# frozen_string_literal: true

lane :ios do
  appicon(
    appicon_image_file: 'spec/fixtures/Themoji.png',
    appicon_devices: %i[ipad iphone ios_marketing watch watch_marketing],
    appicon_path: 'app'
  )
end

lane :ios_splash do
  appicon(
    appicon_image_file: 'spec/fixtures/ThemojiSplash.png',
    appicon_devices: [:universal],
    appicon_path: 'app',
    appicon_name: 'Splash.imageset'
  )
end

lane :android do
  android_appicon(
    appicon_image_file: 'spec/fixtures/Themoji.png',
    appicon_path: 'app/res/mipmap',
    generate_rounded: true
  )
end

lane :android_splash do
  android_appicon(
    appicon_image_file: 'spec/fixtures/ThemojiSplash.png',
    appicon_icon_types: %i[splash_port splash_land],
    appicon_path: 'app/res/drawable',
    appicon_filename: 'splash'
  )
end
