lane :test do
  appicon(
    appicon_image_file: 'spec/fixtures/Themoji.png',
    appicon_devices: [:ipad, :iphone, :ios_marketing, :watch, :watch_marketing]
  )
end

lane :android do
  android_appicon(
    appicon_image_file: 'spec/fixtures/Themoji.png',
    appicon_path: 'app/res/mipmap'
  )
end

lane :android_rounded do
  android_appicon(
    appicon_image_file: 'spec/fixtures/Themoji.png',
    appicon_path: 'app_rounded/res/mipmap',
    generate_rounded: true
  )
end
